#!/bin/sh

echo "----- PACKAGES: -----"

source /etc/os-release

if [ "$ID" = "rocky" ] || [ "$ID" = "fedora" ]; then
    dnf repoquery --userinstalled
elif [ "$ID" = "ubuntu" ] || [ "$ID" = "debian" ]; then
    apt-mark showmanual
fi

