#!/bin/sh

echo "----- INTEGRITY: -----"

source /etc/os-release

if [ "$ID" = "rocky" ] || [ "$ID" = "fedora" ]; then
    sudo rpm -qaV
elif [ "$ID" = "ubuntu" ] || [ "$ID" = "debian" ]; then
    if [ "$1" = "i" ] || [ "$1" = "install" ]; then
        sudo apt install debsums -y
    fi
    sudo debsums -s
fi

