#!/bin/bash
source /etc/os-release

check() {
	if [ $ret -eq 0 ] ; then
		exit
	fi
}



if [[ $ID =~ "ubuntu" ]] || [[ $ID =~ 'debian' ]] || [[ $1 == "apt"  ]]; then
	export DEBIAN_FRONTEND=noninteractive # needed sometimes for apt finniky-ness
	apt-get update --yes
	if ! $(apt-get install --yes debsums 2>/dev/null); then
		while [ $? -ge 1 ]; do 
		echo "There is something wrong with your distro based around apt trying to automatically repair"
		apt-get reinstall --yes apt
		dpkg --configure -a
		done
		apt-get update  --yes 2>/dev/null
		apt-get install --yes debsums 2>/dev/null
	fi
	# find packages that are not matching the proper hashes
	packages=( $(dpkg -S $(debsums -c) | cut -d : -f 1 | sort -u) )
	## add choice thing here
	echo "we are going to install ${packages[@]} please type the ones you dont want removed"
  	read -a my_array
	test=0
	for package in ${packages[@]}; do 
		
		for var in ${my_array[@]}; do
			if [[ $package == $var ]]; then 
			 ((test=1))
			fi
		done

		if [[ test == 0 ]]; then 
			packagestmp=( ${package} ${packagestmp[@]} )
		fi

	done;
	packages=${packagestmp[@]}

	apt-get install --download-only ${packages[@]}
	temp=( $(echo /sys/class/net/*) )
	for interface in ${temp[@]##*/}; do
		$(ip link set $interface down)
	done; unset temp

	systemctl stop chron 2>/dev/null
	apt-get install --reinstall --yes --no-download ${packages[@]}
elif [ "$ID" = "rocky" ] || [ "$ID" = "fedora" ] || [ "$1" = "dnf" ]; then
    dnf reinstall $(rpm -qf $(rpm -Va 2>&1 | grep -vE '^$|prelink:' | sed 's|.* /|/|') | sort -u
fi



#if ${force}; then
 #	halt -f;
#fi
# written by Jasper at RIT 

