#!/bin/bash

user=$1; shift
ip=$1; shift
commands="cd irsec2025"

for arg in "$@"; do
    if [ $arg = "r" ] || [ $arg = "c" ] || [ $arg = "clean" ]; then
        ssh $user@$ip "rm -rf irsec2025"
    elif [ $arg = "i" ] || [ $arg = "install" ]; then
        scp -qr $(pwd) $user@$ip:
    else
        commands+="; echo; $arg"
    fi
done

echo $commands

ssh -t $user@$ip "$commands"

