#!/bin/sh

if [[ -z "$1" ]]; then
    users=("$(whoami)")
else
    IFS=',' read -a users <<< "$1"
fi

for user in "${users[@]}"; do
    password="$(shuf -n 1 set/words.txt)"

    for i in {1..3}; do
        password+="-$(shuf -n 1 set/words.txt)"
    done

    echo -e $user:$password
    echo -e $password | sudo passwd --stdin "$(user)"
done

